# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

EXPOSE 8501
EXPOSE 8000

# ENV HOST='127.0.0.2'
ENV HOST='0.0.0.0'
ENV PORT=8501
# ENV API_URL='http://127.0.0.3:8000'
ENV API_URL='http://localhost:8000'

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
#COPY ./src /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["uvicorn", "--bind", "127.0.0.2:8000", "-k", "uvicorn.workers.UvicornWorker", "app:app_p1"]
CMD [ "python", "app.py" ]