version: '3'

services:
  project1:
    build: 
      context: Project1
      args:
        URL: "http://project2:8000"
    ports:
      - 5000:8000
    volumes:
      - './Project1/src:/app'
    networks:
      - common
    depends_on:
      - project2
  project2:
    build: Project2
    volumes:
      - './Project2/src:/app'
    networks:
      - common
networks:
  common: