version: '3'

services:
  project1:
    build: 
      context: Project1
      args:
        URL: "http://project2/api/v1/project2"
    ports:
      - 5000:80
    volumes:
      - './Project1/src:/app'
    networks:
      - common
    depends_on:
      - project2
  project2:
    build: Project2
    ports:
      - 5001:80
    volumes:
      - './Project2/src:/app'
    networks:
      - common
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project1
      - project2
    networks:
      - common
networks:
  common: